version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bnpl
      POSTGRES_USER: bnpluser
      POSTGRES_PASSWORD: bnplpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5434:5432'

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5673:5672'
      - '15673:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  backend:
    build: .
    command: sh -c "python manage.py migrate && gunicorn bnpl_backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq

  celeryworker:
    build: .
    command: celery -A bnpl_backend worker -l info
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq

  celerybeat:
    build: .
    command: celery -A bnpl_backend beat -l info
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
